# Generated by Django 4.1 on 2022-08-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_widget', '0002_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
